name: Deploy Project

on: push

jobs:
    test:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                ref: main
                # ref: dev
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
    deploy:
        runs-on: ubuntu-latest
        steps:  
          - name: Build Project
            run: npm run build
          #! Simulation of deployment process
          - name: Deploy to Server
            run: echo "Deploying to server..."
